# Generated by Django 6.0.1 on 2026-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdeposit',
            name='gateway_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdeposit',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentdeposit',
            name='pix_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='asaas_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='asaas_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='binance_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
