# Generated by Django 6.0.1 on 2026-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentdeposit_gateway_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
