# Generated by Django 6.0.1 on 2026-09-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='order_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
