# Generated by Django 6.0.1 on 2026-09-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicelist_order_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelist',
            name='order_description',
        ),
    ]
