# Generated by Django 6.0.1 on 2026-09-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_servicelist_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.servicelist'),
        ),
    ]
