# Generated by Django 6.0.1 on 2026-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customerorder_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteservicelist',
            name='referenceid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
