# Generated by Django 6.0.1 on 2026-09-11 01:47

from django.db import migrations


def seed_provider_api(apps, schema_editor):
    Api = apps.get_model('core', 'Api')
    Api.objects.update_or_create(
        id=1,
        defaults={
            'api_name': 'Expert Server',
            'api_type': 'gsm',
            'api_url': 'https://expertserver.com.br/public',
            'api_username': 'enterserver@hotmail.com',
            'api_key': 'IEHZ-FFLC-UUP5-POX4-XUVU-KCJZ-CMFX-FXSH',
            'status': 'Active',
        },
    )


def unseed_provider_api(apps, schema_editor):
    Api = apps.get_model('core', 'Api')
    Api.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remoteservicelist_referenceid'),
    ]

    operations = [
        migrations.RunPython(seed_provider_api, unseed_provider_api),
    ]