# Generated by Django 6.0.1 on 2026-09-11 02:46

from django.db import migrations, models


def enable_api_allow_for_all(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    Customer.objects.filter(api_allow='').update(api_allow='on')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_provider_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='api_allow',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.RunPython(enable_api_allow_for_all, migrations.RunPython.noop),
    ]
