# Generated by Django 6.0.1 on 2026-09-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicelist_api_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydata',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_uses', to='core.customerorder'),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.inventory'),
        ),
    ]
