# Generated by Django 6.0.1 on 2026-09-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customerorder_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='service_type',
            field=models.CharField(choices=[('server_service', 'Server'), ('credit_service', 'Credit'), ('activation_service', 'Activation'), ('imei_service', 'IMEI'), ('method_service', 'Method')], default='server_service', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='service_type',
            field=models.CharField(choices=[('Server Service', 'Server Service'), ('Credit Service', 'Credit Service'), ('Activation Service', 'Activation Service'), ('IMEI Service', 'IMEI Service'), ('Method Service', 'Method Service')], default='Server Service', max_length=50),
        ),
    ]
