# Generated by Django 6.0.1 on 2026-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_customerorder_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='collect_login',
            field=models.BooleanField(default=True, verbose_name='Pedir usuário e e-mail na compra'),
        ),
    ]
