# Generated by Django 6.0.1 on 2026-09-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_servicelist_collect_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='collect_email',
            field=models.BooleanField(default=True, verbose_name='Pedir e-mail da ferramenta na compra'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='collect_login',
            field=models.BooleanField(default=True, verbose_name='Pedir usuário na compra'),
        ),
    ]
