# Generated by Django 6.0.1 on 2026-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_servicelist_collect_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelist',
            name='collect_email',
        ),
        migrations.AddField(
            model_name='servicelist',
            name='collect_fields',
            field=models.CharField(choices=[('both', 'Usuário e e-mail'), ('user', 'Somente usuário'), ('email', 'Somente e-mail')], default='both', max_length=10, verbose_name='Dados a solicitar na compra'),
        ),
        migrations.AlterField(
            model_name='servicelist',
            name='collect_login',
            field=models.BooleanField(default=True, verbose_name='Pedir usuário/e-mail na compra'),
        ),
    ]
