# Generated by Django 6.0.1 on 2026-09-13 01:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_servicelist_collect_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='price_markup',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Margem (%) adicionada sobre o custo do provedor.', max_digits=12),
        ),
        migrations.AddField(
            model_name='api',
            name='price_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Câmbio USD→BRL usado para sugerir preço. 0 = não converter.', max_digits=12),
        ),
    ]
