# Generated by Django 6.0.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_api_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_pin',
            field=models.CharField(blank=True, help_text='PIN mestre usado na autenticação de compras (ex.: RITUNLOCKER).', max_length=255, null=True),
        ),
    ]