# Generated by Django 6.0.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_api_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='collect_extras',
            field=models.CharField(blank=True, choices=[('anydesk', 'Acesso do AnyDesk'), ('lock_photo', 'Foto da tela de bloqueio'), ('whatsapp', 'WhatsApp')], default='', max_length=120, verbose_name='Dados adicionais a solicitar na compra'),
        ),
    ]