# Generated by Django 6.0.1 on 2026-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_servicelist_collect_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='collect_fields',
            field=models.CharField(choices=[('both', 'Usuário e e-mail'), ('user', 'Somente usuário'), ('email', 'Somente e-mail'), ('serial', 'Serial Number')], default='both', max_length=10, verbose_name='Dados a solicitar na compra'),
        ),
    ]