# Generated by Django 6.0.1 on 2026-09-14 02:05

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_servicelist_collect_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_base_url',
            field=models.CharField(blank=True, help_text='URL base da API Vepay (ex.: https://api.vepay.forkao.com).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Câmbio BRL→Kwanza usado para cobrar no Multicaixa Express. 0 = desativado.', max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_receiving_number',
            field=models.CharField(blank=True, help_text='Número MULTICAIXA Express de destino (pré-cadastrado no Vepay).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_sandbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='vepay_webhook_token',
            field=models.CharField(blank=True, help_text='Token usado na URL do webhook Vepay (configure a mesma URL no console Vepay).', max_length=64, null=True),
        ),
    ]