# Generated by Django 6.0.1 on 2026-09-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paymentgateway_vepay_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_api_key',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_base_url',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_rate',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_receiving_number',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_sandbox',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='vepay_webhook_token',
        ),
    ]