# Generated by Django 6.0.1 on 2026-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_servicelist_collect_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
