# Generated by Django 6.0.1 on 2026-09-16 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_paymentdeposit_gateway_fee_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
