# Generated by Django 6.0.1 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_customerorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='panel_url',
            field=models.CharField(blank=True, help_text='URL do painel web do provedor (ex.: https://ritunlocker.com). Usado para buscar a resposta completa (login + senha) quando a API não devolve a senha. Aceita {trx} para a URL do pedido.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='panel_user',
            field=models.CharField(blank=True, help_text='Login do painel web (não vai pro cliente).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='panel_pass',
            field=models.CharField(blank=True, help_text='Senha do painel web (não vai pro cliente).', max_length=255, null=True),
        ),
    ]
