from django.urls import path

from . import public_api, views, views_admin

urlpatterns = [
    path('admin-panel/', views_admin.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/orders/pending/', views_admin.admin_orders_unseen, name='admin_orders_unseen'),
    path('admin-panel/orders/<str:status>/', views_admin.admin_orders, name='admin_orders'),
    path('admin-panel/orders/<int:order_id>/update/', views_admin.admin_order_update, name='admin_order_update'),
    path('admin-panel/orders/<int:order_id>/refund/', views_admin.admin_order_refund, name='admin_order_refund'),
    path('admin-panel/orders/<int:order_id>/delete/', views_admin.admin_order_delete, name='admin_order_delete'),
    path('admin-panel/invoices/', views_admin.admin_invoice_list, name='admin_invoice_list'),
    path('admin-panel/invoices/<int:invoice_id>/delete/', views_admin.admin_invoice_delete, name='admin_invoice_delete'),
    path('admin-panel/invoices/<int:invoice_id>/status/', views_admin.admin_invoice_toggle_paid, name='admin_invoice_toggle_paid'),
    path('admin-panel/customers/', views_admin.admin_customer_list, name='admin_customer_list'),
    path('admin-panel/customers/<int:customer_id>/api-toggle/', views_admin.admin_customer_api_toggle, name='admin_customer_api_toggle'),
    path('admin-panel/customers/<int:customer_id>/refund/', views_admin.admin_customer_refund, name='admin_customer_refund'),
    path('admin-panel/customers/<int:customer_id>/edit/', views_admin.admin_customer_edit, name='admin_customer_edit'),
    path('admin-panel/customers/<int:customer_id>/password/', views_admin.admin_customer_password, name='admin_customer_password'),
    path('admin-panel/customers/<int:customer_id>/delete/', views_admin.admin_customer_delete, name='admin_customer_delete'),
    path('admin-panel/customers/<int:customer_id>/promote/', views_admin.admin_customer_promote, name='admin_customer_promote'),
    path('admin-panel/inventory/', views_admin.admin_inventory_list, name='admin_inventory_list'),
    path('admin-panel/inventory/quick-add/', views_admin.admin_inventory_quick_add, name='admin_inventory_quick_add'),
    path('admin-panel/inventory/new/', views_admin.admin_inventory_new, name='admin_inventory_new'),
    path('admin-panel/inventory/<int:inventory_id>/', views_admin.admin_inventory_detail, name='admin_inventory_detail'),
    path('admin-panel/inventory/<int:inventory_id>/update/', views_admin.admin_inventory_update, name='admin_inventory_update'),
    path('admin-panel/inventory/<int:inventory_id>/delete/', views_admin.admin_inventory_delete, name='admin_inventory_delete'),
    path('admin-panel/inventory/<int:inventory_id>/add/', views_admin.admin_inventory_add, name='admin_inventory_add'),
    path('admin-panel/inventory/items/<int:data_id>/edit/', views_admin.admin_inventory_edit, name='admin_inventory_edit'),
    path('admin-panel/inventory/items/<int:data_id>/toggle/', views_admin.admin_inventory_toggle, name='admin_inventory_toggle'),
    path('admin-panel/inventory/items/<int:data_id>/delete/', views_admin.admin_inventory_data_delete, name='admin_inventory_data_delete'),
    path('admin-panel/orders/<int:order_id>/deliver-credential/', views_admin.admin_order_deliver_credential, name='admin_order_deliver_credential'),
    path('admin-panel/services/<str:svtype>/', views_admin.admin_service_list, name='admin_service_list'),
    path('admin-panel/services/<str:svtype>/new/', views_admin.admin_service_new, name='admin_service_new'),
    path('admin-panel/services/<str:svtype>/<int:service_id>/edit/', views_admin.admin_service_edit, name='admin_service_edit'),
    path('admin-panel/services/<str:svtype>/<int:service_id>/toggle-api/', views_admin.admin_service_toggle_api, name='admin_service_toggle_api'),
    path('admin-panel/services/<str:svtype>/<int:service_id>/toggle-login/', views_admin.admin_service_toggle_login, name='admin_service_toggle_login'),
    path('admin-panel/services/<str:svtype>/<int:service_id>/delete/', views_admin.admin_service_delete, name='admin_service_delete'),
    path('admin-panel/services/<str:svtype>/<int:service_id>/move/', views_admin.admin_service_move, name='admin_service_move'),
    path('admin-panel/currencies/', views_admin.admin_currency_list, name='admin_currency_list'),
    path('admin-panel/currencies/<int:currency_id>/update/', views_admin.admin_currency_update, name='admin_currency_update'),
    path('admin-panel/gateways/', views_admin.admin_gateway_list, name='admin_gateway_list'),
    path('admin-panel/gateways/<int:gateway_id>/update/', views_admin.admin_gateway_update, name='admin_gateway_update'),
    path('admin-panel/api/<int:api_id>/', views_admin.admin_api_detail, name='admin_api_detail'),
    path('admin-panel/apis/', views_admin.admin_api_list, name='admin_api_list'),
    path('admin-panel/apis/new/', views_admin.admin_api_new, name='admin_api_new'),
    path('admin-panel/apis/<int:api_id>/update/', views_admin.admin_api_update, name='admin_api_update'),
    path('admin-panel/apis/<int:api_id>/test/', views_admin.admin_api_test, name='admin_api_test'),
path('admin-panel/apis/<int:api_id>/import/', views_admin.admin_api_import, 
name='admin_api_import'),
    path('admin-panel/apis/link/', views_admin.admin_api_link, name='admin_api_link'),
    path('admin-panel/setting/', views_admin.admin_setting, name='admin_setting'),
    path('admin-panel/logout/', views_admin.admin_logout, name='admin_logout'),

    path('admin-panel/sliders/', views_admin.admin_slider_list, name='admin_slider_list'),
    path('admin-panel/sliders/upload-image/', views_admin.admin_slider_upload_image, name='admin_slider_upload_image'),
    path('admin-panel/sliders/new/', views_admin.admin_slider_new, name='admin_slider_new'),
    path('admin-panel/sliders/<int:slider_id>/edit/', views_admin.admin_slider_edit, name='admin_slider_edit'),
    path('admin-panel/sliders/<int:slider_id>/delete/', views_admin.admin_slider_delete, name='admin_slider_delete'),

    path('admin-panel/pages/', views_admin.admin_page_list, name='admin_page_list'),
    path('admin-panel/pages/new/', views_admin.admin_page_new, name='admin_page_new'),
    path('admin-panel/pages/<int:page_id>/edit/', views_admin.admin_page_edit, name='admin_page_edit'),
    path('admin-panel/pages/<int:page_id>/delete/', views_admin.admin_page_delete, name='admin_page_delete'),

    path('', views.homepage, name='homepage'),
    path('public/api/index.php', public_api.public_api, name='public_api'),
    path('public/api/', public_api.public_api, name='public_api_index'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('change-theme-mode/', views.change_theme_mode, name='change_theme_mode'),
    path('service/<slug:slug>/', views.server_view, name='service_view'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),

    path('customer/dashboard/', views.customer_dashboard, name='customer_dashboard'),
    path('customer/profile/', views.customer_profile, name='customer_profile'),
    path('customer/order-history/', views.customer_order_history, name='customer_order_history'),
    path('customer/statement/', views.customer_statement, name='customer_statement'),
    path('customer/invoice/', views.customer_invoice_list, name='customer_invoice'),
    path('customer/invoice/<int:invoice_id>/', views.customer_invoice_detail, name='customer_invoice_detail'),
    path('customer/add-balance/', views.customer_add_balance, name='customer_add_balance'),
    path('customer/deposit/', views.customer_deposit, name='customer_deposit'),
    path('customer/checkout/<int:invoice_id>/', views.checkout, name='checkout'),
    path('customer/checkout/<int:invoice_id>/pay/', views.gateway_pay, name='gateway_pay'),
    path('customer/pay/<int:invoice_id>/', views.payment_page, name='payment_page'),
    path('customer/pay/<int:invoice_id>/status/', views.payment_status, name='payment_status'),
    path('payment/asaas/webhook/', views.asaas_webhook, name='asaas_webhook'),
    path('payment/binance/webhook/', views.binance_webhook, name='binance_webhook'),
    path('customer/submit-order/', views.submit_order, name='submit_order'),

    path('page/<slug:slug>/', views.page_view, name='page_view'),
]
